# fly.toml app configuration file generated for pitchdeckgenerator on 2024-11-07T10:21:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pitchdeckgenerator'
primary_region = 'ams'

[build]
  builder = "heroku/buildpacks:20" # optional, uses Heroku buildpacks


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
